%Create figure window with the title Project #2 - Jayce Jones
        figure('Name','Application Login','NumberTitle','off','ToolBar','None','Position',[0,0,350,500]);
        
        
%Create a pushbutton to select and open a new source image as the "current" image
        uicontrol('Style','text','String','Maintenance','Position',[100,400,150,100]);
        
        uicontrol('Style','text','String','Toggle Inputs','Position',[100,380,150,100]);
        
bg = uibuttongroup('Visible','off','Position',[0,0,1,.9]);

%Right/Left Up/Down Length Width
r3 = uicontrol(bg,'Style','radiobutton',...
                  'String','Home All',...
                  'Position',[10 420 100 20],...
                  'HandleVisibility','off');
              
r3 = uicontrol(bg,'Style','radiobutton',...
                  'String','Home Feed Arm',...
                  'Position',[10 400 100 20],...
                  'HandleVisibility','off');
              
r4 = uicontrol(bg,'Style','radiobutton',...
                  'String','Home Die Head Assembly',...
                  'Position',[10 380 150 20],...
                  'HandleVisibility','off');
              
r5 = uicontrol(bg,'Style','radiobutton',...
                  'String','Home Vise Assembly #1',...
                  'Position',[10 360 150 20],...
                  'HandleVisibility','off');
              
r6 = uicontrol(bg,'Style','radiobutton',...
                  'String','Home Vise Assembly #2',...
                  'Position',[10 340 150 20],...
                  'HandleVisibility','off');
              
r7 = uicontrol(bg,'Style','radiobutton',...
                  'String','Open/Close Vise #1',...
                  'Position',[10 320 150 20],...
                  'HandleVisibility','off');
              
r8 = uicontrol(bg,'Style','radiobutton',...
                  'String','Open/Close Vise #2',...
                  'Position',[10 300 150 20],...
                  'HandleVisibility','off');
              
r1 = uicontrol(bg,'Style',...
                  'radiobutton',...
                  'String','Open Collet',...
                  'Position',[10 280 100 20],...
                  'HandleVisibility','off');
              
r2 = uicontrol(bg,'Style','radiobutton',...
                  'String','Close Collet',...
                  'Position',[10 260 100 20],...
                  'HandleVisibility','off');
              
r9 = uicontrol(bg,'Style','radiobutton',...
                  'String','Fetch Pipe',...
                  'Position',[10 240 150 20],...
                  'HandleVisibility','off');
              
r10 = uicontrol(bg,'Style','radiobutton',...
                  'String','Extend Feed Arm',...
                  'Position',[10 220 150 20],...
                  'HandleVisibility','off');
              
r11 = uicontrol(bg,'Style','radiobutton',...
                  'String','Retract Feed Arm',...
                  'Position',[10 200 150 20],...
                  'HandleVisibility','off');
              
r12 = uicontrol(bg,'Style','radiobutton',...
                  'String','Restart Sensors',...
                  'Position',[10 140 150 20],...
                  'HandleVisibility','off');
              
r13 = uicontrol(bg,'Style','radiobutton',...
                  'String','Start Bending Sequence',...
                  'Position',[10 180 150 20],...
                  'HandleVisibility','off');
              
r14 = uicontrol(bg,'Style','radiobutton',...
                  'String','Stop Bending Sequence',...
                  'Position',[10 160 150 20],...
                  'HandleVisibility','off');
              
bg.Visible = 'on';